packages:
  - "apps/*"
  - "packages/*"
  - "tests"
minimumReleaseAgeExclude:
  - '@changesets/apply-release-plan@8.1.1'
  - '@changesets/cli@3.0.3'
  - '@changesets/config@4.0.1'
  - '@turbo/darwin-64@2.10.13'
  - '@turbo/darwin-arm64@2.10.13'
  - '@turbo/linux-64@2.10.13'
  - '@turbo/linux-arm64@2.10.13'
  - '@turbo/windows-64@2.10.13'
  - '@turbo/windows-arm64@2.10.13'
  - turbo@2.10.13
