import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";

export const THEME_FILE = "beton.css";

type CssObject = { [key: string]: string | CssObject };

export function objectToCss(object: CssObject, indent = ""): string {
  const lines: string[] = [];
  for (const [key, value] of Object.entries(object)) {
    if (typeof value === "object") {
      lines.push(`${indent}${key} {`, objectToCss(value, `${indent}  `), `${indent}}`);
    } else {
      lines.push(`${indent}${key}: ${value};`);
    }
  }
  return lines.join("\n");
}

/**
 * Rebuilds the token stylesheet from a registry item: `cssVars.theme` becomes
 * the @theme block (with keyframes, which Tailwind reads from @theme) and the
 * remaining `css` rules follow it.
 */
export function themeFromItem(item: {
  cssVars?: { theme?: Record<string, string> };
  css?: CssObject;
}): CssObject {
  const theme: CssObject = {};
  for (const [name, value] of Object.entries(item.cssVars?.theme ?? {})) {
    theme[`--${name.replace(/^--/, "")}`] = value;
  }
  const rest: CssObject = {};
  for (const [key, value] of Object.entries(item.css ?? {})) {
    if (key.startsWith("@keyframes")) theme[key] = value;
    else rest[key] = value;
  }
  return { "@theme": theme, ...rest };
}

export function themeStylesheet(css: CssObject): string {
  return [
    "/*",
    " * Béton theme. Generated by beton-ui; safe to edit.",
    " * Retheme by changing the semantic tokens (primary, danger, surface...).",
    " */",
    "",
    objectToCss(css),
    "",
  ].join("\n");
}

const TAILWIND_IMPORT = /@import\s+(["'])tailwindcss\1[^;]*;/;

export interface ThemeResult {
  themePath: string;
  /** "written": created or replaced; "unchanged": already current; "kept": differs, left alone. */
  theme: "written" | "unchanged" | "kept";
  addedImport: boolean;
}

/**
 * Writes beton.css beside the global stylesheet and imports it right after
 * Tailwind, so the tokens join the Tailwind theme.
 */
export function installTheme(
  cwd: string,
  cssFile: string,
  css: CssObject,
  overwrite: boolean,
): ThemeResult {
  const stylesheet = join(cwd, cssFile);
  if (!existsSync(stylesheet)) {
    throw new Error(`Stylesheet not found: ${cssFile}`);
  }
  const themePath = join(dirname(stylesheet), THEME_FILE);
  const generated = themeStylesheet(css);
  let theme: ThemeResult["theme"] = "written";
  if (existsSync(themePath) && readFileSync(themePath, "utf8") === generated) {
    theme = "unchanged";
  } else if (existsSync(themePath) && !overwrite) {
    theme = "kept";
  } else {
    writeFileSync(themePath, generated);
  }

  const source = readFileSync(stylesheet, "utf8");
  const importLine = `@import "./${basename(themePath)}";`;
  if (source.includes(importLine)) return { themePath, theme, addedImport: false };

  const match = source.match(TAILWIND_IMPORT);
  const next = match
    ? source.replace(match[0], `${match[0]}\n${importLine}`)
    : `@import "tailwindcss";\n${importLine}\n\n${source}`;
  writeFileSync(stylesheet, next);
  return { themePath, theme, addedImport: true };
}
